### ISSUE TITLE
Default redirect to main locale, if index.i18n.html is omitted

### ISSUE THREAD

**Issue by donaldpipowitch** [Mercateo/ws#19]
@otbe What do you think. We introduced `index.i18n.html` to either redirect to the mail locale or to integrate a language switcher or some sort of prelude page. In localised projects without `index.i18n.html` we'll get an '404' on hitting `/`. Do you think it is sensible to generate a redirect to the main locale by default, but only if _no_ `index.i18n.html` is present?

**Comment by otbe** [comment]
+1 :)

**Comment by donaldpipowitch** [comment]
Won't fix. Not needed in `ws@2`.
