### ISSUE TITLE
Copy static files to dist without hashes

### ISSUE THREAD

**Issue by floric** [Mercateo/ws#27]
Hey :)

do we have a feature to copy a whole folder (structure) of static files (resources) without referencing them manually in the code and adding hashes to get hashed copies into the main dist-folder?

Example:
I have a folder "static/favicons/" with some icons in my src-folder. I'd like the WS Tool to copy the entire folder without touching the file names so I can reference them in my index.html file. And I don't like to use an additional webpack loader to copy the files but rely fully on the WS Tool. It might be good, if there would a step checking in src/ oder somewhere else for a static folder and copying all it's content to the dist folder without touching it.

What do you think?

**Comment by floric** [comment]
If you like the idea, I could work on a PR.

**Comment by donaldpipowitch** [comment]
I think you can do that already, if you _really_ don't want file hashes. Just use this:

```js
const assetsContext = require.context('copy-loader!./static/favicons', true, /\.(png|xml|ico|json)$/);
assetsContext.keys().forEach(assetsContext);
```

This copies all files ending with `.png`, `.xml`, `.ico` or `.json` inside a `./static/favicons` directory into your output directory. So basically it copies `src/static/favicons/*.(png|xml|ico|json)` to `dist/static/favicons/*.(png|xml|ico|json)` or `dist-release/static/favicons/*.(png|xml|ico|json)`.

👍 

Feel free to close the issue, if it works for you.

**Comment by floric** [comment]
ah ok. I think this will work. But this would still bypass the WS functionalities by using a webpack loader directly. I think it could be nice to get this done automatically without extra code and the direct dependency to a webpack loader. If the WS Tool would be a blackbox, I wouldn't know that webpack is used and loaders exist and can be used.
But I'll give it a try at home and see if this would works. :)
